services:
  accounts:
    image: rarewind/bank-accounts:v1
    container_name: bank-accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
  cards:
    image: rarewind/bank-cards:v1
    container_name: bank-cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
  loans:
    image: rarewind/bank-loans:v1
    container_name: bank-loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
networks:
  bank-network:
    driver: "bridge"