services:
  accountsDB:
    image: mysql
    container_name: accountsDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsDB
    extends:
      file: common-config.yml
      service: microservice-db-config
  loansDB:
    image: mysql
    container_name: loansDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansDB
    extends:
      file: common-config.yml
      service: microservice-db-config
  cardsDB:
    image: mysql
    container_name: cardsDB
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672" # for activities
      - "15672:15672" # for management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: rarewind/bank-configserver:v3
    container_name: bank-configserver-ms-prod
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s # if command failed: retry after 10s
      timeout: 5s # wait for response up-to 5s
      retries: 10 # if command failed: retry up-to 10 times
      start_period: 10s # run the health check command after 10s
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: rarewind/bank-accounts:v4
    container_name: bank-accounts-ms-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsDB:3306/accountsDB"
    depends_on:
      accountsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: rarewind/bank-cards:v4
    container_name: bank-cards-ms-prod
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsDB:3306/cardsDB"
    depends_on:
      cardsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: rarewind/bank-loans:v4
    container_name: bank-loans-ms-prod
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansDB:3306/loansDB"
    depends_on:
      loansDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  bank-network:
    driver: "bridge"